modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
    modId = "floodworld"
    version = "1.4.0"
    displayName = "FloodWorld"
    description = "Floods your world by generating water instead of air below a certain y-level."

[[dependencies.floodworld]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.floodworld]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.floodworld]]
    modId = "cloth_config"
    type = "optional"
    versionRange = "*"
    ordering = "NONE"
    side = "CLIENT"

[[mixins]]
    config = "floodworld.mixins.json"
